### ISSUE TITLE
fit_tellu crash (e2ds_to_s1d IUV Spline)

### ISSUE THREAD

**Issue by njcuk9999** [njcuk9999/apero-drs#650]
Have a somewhat rare instance of fit_tellu crashing due to a IUV Spline with too few points - (require number of points > k + 1) 
Seems to be after the pre-cleaning we get more NaNs --> some section of the spline has too few points.

Example error:
```python
E[01-010-00001]: Unhandled error has occurred: Error <class 'apero.core.math.exceptions.DrsMathException'>  
Traceback (most recent call last): 
File "/spirou/drs/apero-drs/apero/core/core/drs_startup.py", line 355, in run  
llmain = func(recipe, params)                         
File "/spirou/drs/apero-drs/apero/recipes/spirou/obj_fit_tellu_spirou.py", line 265, in __main__ 
fiber=fiber, kind='corrected sp')
File "/spirou/drs/apero-drs/apero/science/extract/general.py", line 1039, in e2ds_to_s1d
spline_sp = mp.iuv_spline(owave[valid], oe2ds, k=5, ext=1)
File "/spirou/drs/apero-drs/apero/core/math/general.py", line 263, in iuv_spline
raise DrsMathException(emsg.format(*eargs))                                                                                                                                                             apero.core.math.exceptions.DrsMathException: IUV Spline len(x) < k+1
k=5 
len(x) = 2
x=[1389.24744801 1389.25679936] 
y=[2259.08097381 1598.13539679]  
```

Example runs (from priority 1):
```
obj_fit_tellu_spirou.py 2019-09-24 2437993o_pp_e2dsff_AB.fits
obj_fit_tellu_spirou.py 2019-12-05 2464025o_pp_e2dsff_AB.fits
obj_fit_tellu_spirou.py 2020-09-04 2512595o_pp_e2dsff_AB.fits
obj_fit_tellu_spirou.py 2020-09-04 2512597o_pp_e2dsff_AB.fits
obj_fit_tellu_spirou.py 2019-09-20 2437649o_pp_e2dsff_AB.fits
obj_fit_tellu_spirou.py 2019-09-24 2437993o_pp_e2dsff_AB.fits
obj_fit_tellu_spirou.py 2019-12-05 2464024o_pp_e2dsff_AB.fits
```

**Comment by eartigau** [comment]
`18:09:44.456-!|cal_ccf_spirou| E[01-010-00001]: Unhandled error has occurred: Error <class 'apero.core.math.exceptions.DrsMathException'> 
18:09:44.457-!|cal_ccf_spirou| 
18:09:44.458-!|cal_ccf_spirou| Traceback (most recent call last):
18:09:44.458-!|cal_ccf_spirou|  File "/spirou/drs/apero-drs/apero/core/core/drs_startup.py", line 355, in run
18:09:44.459-!|cal_ccf_spirou|    llmain = func(recipe, params)
18:09:44.459-!|cal_ccf_spirou|  File "/spirou/drs/apero-drs/apero/recipes/spirou/cal_ccf_spirou.py", line 196, in __main__
18:09:44.460-!|cal_ccf_spirou|    rv_props1 = velocity.compute_ccf_science(params, recipe, *cargs)
18:09:44.460-!|cal_ccf_spirou|  File "/spirou/drs/apero-drs/apero/science/velocity/general.py", line 740, in compute_ccf_science
18:09:44.461-!|cal_ccf_spirou|    fit_type, fiber)
18:09:44.461-!|cal_ccf_spirou|  File "/spirou/drs/apero-drs/apero/science/velocity/general.py", line 1080, in ccf_calculation
18:09:44.462-!|cal_ccf_spirou|    spline_sp = mp.iuv_spline(wa_ord[good], sp_ord[good], k=5, ext=1)
18:09:44.463-!|cal_ccf_spirou|  File "/spirou/drs/apero-drs/apero/core/math/general.py", line 263, in iuv_spline
18:09:44.463-!|cal_ccf_spirou|    raise DrsMathException(emsg.format(*eargs))
18:09:44.464-!|cal_ccf_spirou| apero.core.math.exceptions.DrsMathException: IUV Spline len(x) < k+1 
18:09:44.464-!|cal_ccf_spirou| 	k=5
18:09:44.465-!|cal_ccf_spirou| 	len(x) = 4
18:09:44.465-!|cal_ccf_spirou| 	x=[1391.27569334 1391.29412237 1391.31254891 1391.32176124]
18:09:44.466-!|cal_ccf_spirou| 	y=[126.01776363 106.41446884  78.81247772  56.62251111]
18:09:44.466-!|cal_ccf_spirou| 
18:09:44.946-*|cal_ccf_spirou| ***************************************************************************
18:09:45.016-@|cal_ccf_spirou| W[40-003-00005]: Recipe cal_ccf_spirou has NOT been successfully completed
18:09:45.089-*|cal_ccf_spirou| ***************************************************************************
`

**Comment by eartigau** [comment]
18:09:44.456-!|cal_ccf_spirou| E[01-010-00001]: Unhandled error has occurred: Error <class 'apero.core.math.exceptions.DrsMathException'> 
18:09:44.457-!|cal_ccf_spirou| 
18:09:44.458-!|cal_ccf_spirou| Traceback (most recent call last):
18:09:44.458-!|cal_ccf_spirou|  File "/spirou/drs/apero-drs/apero/core/core/drs_startup.py", line 355, in run
18:09:44.459-!|cal_ccf_spirou|    llmain = func(recipe, params)
18:09:44.459-!|cal_ccf_spirou|  File "/spirou/drs/apero-drs/apero/recipes/spirou/cal_ccf_spirou.py", line 196, in __main__
18:09:44.460-!|cal_ccf_spirou|    rv_props1 = velocity.compute_ccf_science(params, recipe, *cargs)
18:09:44.460-!|cal_ccf_spirou|  File "/spirou/drs/apero-drs/apero/science/velocity/general.py", line 740, in compute_ccf_science
18:09:44.461-!|cal_ccf_spirou|    fit_type, fiber)
18:09:44.461-!|cal_ccf_spirou|  File "/spirou/drs/apero-drs/apero/science/velocity/general.py", line 1080, in ccf_calculation
18:09:44.462-!|cal_ccf_spirou|    spline_sp = mp.iuv_spline(wa_ord[good], sp_ord[good], k=5, ext=1)
18:09:44.463-!|cal_ccf_spirou|  File "/spirou/drs/apero-drs/apero/core/math/general.py", line 263, in iuv_spline
18:09:44.463-!|cal_ccf_spirou|    raise DrsMathException(emsg.format(*eargs))
18:09:44.464-!|cal_ccf_spirou| apero.core.math.exceptions.DrsMathException: IUV Spline len(x) < k+1 
18:09:44.464-!|cal_ccf_spirou| 	k=5
18:09:44.465-!|cal_ccf_spirou| 	len(x) = 4
18:09:44.465-!|cal_ccf_spirou| 	x=[1391.27569334 1391.29412237 1391.31254891 1391.32176124]
18:09:44.466-!|cal_ccf_spirou| 	y=[126.01776363 106.41446884  78.81247772  56.62251111]
18:09:44.466-!|cal_ccf_spirou| 
18:09:44.946-*|cal_ccf_spirou| ***************************************************************************
18:09:45.016-@|cal_ccf_spirou| W[40-003-00005]: Recipe cal_ccf_spirou has NOT been successfully completed
18:09:45.089-*|cal_ccf_spirou| ***************************************************************************

**Comment by njcuk9999** [comment]
Okay fix to this is as follows:
1. check for len(x[~nanmask]) and len(y[~nanmask]) < (k+1)
2. instead of returning the spline class return a class that gives all NaNs for the input x to respline at:
        `apero/core/math/general.py`

```python
class NanSpline:
    def __init__(self, emsg: str, x: Union[np.ndarray, None] = None,
                 y: Union[np.ndarray, None] = None, **kwargs):
        """
        This is used in place of scipy.interpolateInterpolatedUnivariateSpline
        (Any spline following this will return all NaNs)

        :param emsg: str, the error that means we have to use the NanSpline
        """
        self.emsg = str(emsg)
        self.x = copy.deepcopy(x)
        self.y = copy.deepcopy(y)
        self.kwargs = copy.deepcopy(kwargs)

    def __repr__(self) -> str:
        """
        String representation of the class

        :return: string representation
        """
        return 'NanSpline: \n' + self.emsg

    def __str__(self) -> str:
        """
        String representation of the class

        :return: string representation
        """
        return self.__repr__()

    def __call__(self, x: np.ndarray, nu: int = 0,
                 ext: Union[int, None] = None) -> np.ndarray:
        """
        Return a vector of NaNs (this means the spline failed due to
        less points

        This is used in place of scipy.interpolateInterpolatedUnivariateSpline

        Parameters
        ----------
        x : array_like
            A 1-D array of points at which to return the value of the smoothed
            spline or its derivatives. Note: x can be unordered but the
            evaluation is more efficient if x is (partially) ordered.
        nu  : int
            The order of derivative of the spline to compute.
        ext : int
            Controls the value returned for elements of ``x`` not in the
            interval defined by the knot sequence.

            * if ext=0 or 'extrapolate', return the extrapolated value.
            * if ext=1 or 'zeros', return 0
            * if ext=2 or 'raise', raise a ValueError
            * if ext=3 or 'const', return the boundary value.

            The default value is 0, passed from the initialization of
            UnivariateSpline.

        """
        return np.repeat(np.nan, len(x))


def iuv_spline(x, y, **kwargs):

    # copy x and y
    x, y = np.array(x), np.array(y)
    # find all NaN values
    nanmask = ~np.isfinite(y)

    # deal with dimensions error (on k)
    #   otherwise get   dfitpack.error: (m>k) failed for hidden m
    if kwargs.get('k', None) is not None:
        # deal with to few parameters in x
        if len(x[~nanmask]) < (kwargs['k'] + 1):
            # raise exception if len(x) is bad
            emsg = ('IUV Spline len(x) < k+1 '
                    '\n\tk={0}\n\tlen(x) = {1}'
                    '\n\tx={2}\n\ty={3}')
            eargs = [kwargs['k'], len(x), str(x)[:70], str(y)[:70]]
            # return a nan spline
            return NanSpline(emsg.format(*eargs), x=x, y=y, **kwargs)
        if len(y[~nanmask]) < (kwargs['k'] + 1):
            # raise exception if len(x) is bad
            emsg = ('IUV Spline len(y) < k+1 '
                    '\n\tk={0}\n\tlen(y) = {1}'
                    '\n\tx={2}\n\ty={3}')
            eargs = [kwargs['k'], len(y), str(x)[:70], str(y)[:70]]
            # return a nan spline
            return NanSpline(emsg.format(*eargs), x=x, y=y, **kwargs)

    if np.sum(~nanmask) < 2:
        y = np.repeat(np.nan, len(x))
    elif np.sum(~nanmask) == 0:
        y = np.repeat(np.nan, len(x))
    else:
        # replace all NaN's with linear interpolation
        badspline = InterpolatedUnivariateSpline(x[~nanmask], y[~nanmask],
                                                 k=1, ext=1)
        y[nanmask] = badspline(x[nanmask])
    # return spline
    return InterpolatedUnivariateSpline(x, y, **kwargs)
```
