### ISSUE TITLE
Add zsh support

### ISSUE THREAD

**Issue by vandalt** [njcuk9999/apero-drs#656]
The APERO prompt behaves weirdly when launching from zsh. Given that this is the default prompt on some systems (including recent MacOS), I will make separate profile files for this shell.

Workaround now:
1. Put the alias in the `.bashrc` (or tcsh/sh)
2. Launch `bash` in interactive mode (just type the command in your terminal, or tcsh/sh)
3. Activate `apero-env` (you'll need conda in bash, just copy the conda block from your zshrc to your bashrc if you need to) and activate your profile from bash.

**Comment by njcuk9999** [comment]
Yer I wouldn't expect zsh to work with the bash or sh script.

If you can get one of the standard `{profile}.bash.setup` files to work with zsh (i.e. make a `{profile}.zsh.setup` we can then fix the master copies and include those as standard in any installation.

Note the master copies are stored here but cannot be run themselves (paths are inserted as part of the installation):

`../apero-drs/apero/tools/resources/setup/`

You'll have to fix both a `{profile}.{shell}.setup` and a `{profile}.{shell}.setup.profile`  but worst case they should both have the minimum functionality of the  `{profile}.{shell}.setup` file (The other just adds a custom prompt so isn't 100% necessary, but the file existing is).

**Comment by njcuk9999** [comment]
@vandalt  Did you ever write one of these for zsh? If so I'll add it to the ones that are copied in (and add instructions to use it)

**Comment by vandalt** [comment]
No sorry, I've mostly worked on the tests since then. I can give it a try this weekend, and make sure it displays properly on my laptop.

**Comment by njcuk9999** [comment]
No worries - it isn't urgent I was just trying to clear up some issues

**Comment by vandalt** [comment]
Closing this now that #666 is merged in the 0.7 "work" branch.
