### ISSUE TITLE
Nb of spectra used in tell template

### ISSUE THREAD

**Issue by clairem789** [njcuk9999/apero-drs#657]
It would be valuable to have a keyword containing the number of spectra validated in the production of a telluric template (those with SNR>threshold if this is the only used criterium). The information could be present already, but I couln't find it. Thanks!

**Comment by clairem789** [comment]
and the date when this template was produced

**Comment by njcuk9999** [comment]
This is already in the 0.7 build - note that the date the template was produced is already there in 0.6 - though seems the headers are a little bit weird - it's in the first extension (DRSPDATE - the DRS Processed date - as with most files) - I'll have to investigate whats going on with the headers for the Templates as I don't know why this isn't in the primary extension.

In addition to this, there will be a hash code that will be unique to the list of files in the template - so you will know when a template should be exactly the same - (however, this does not mean the individual content of the files that go into the template couldn't change) the three keys add in the template will be as follows (these keys will be pushed into the telluric corrected files along with the Template file name to keep track of what was used:
- MTPNFILE - Number of files used to make the template
- MTP_HASH - Unique hash for input template files
- MTP_TIME - Time template was created

**Comment by njcuk9999** [comment]
Note in the template (even in version 0.6) there is also a second extension that contains a fits table - this has a list of all e2ds files used in that template. You can open it with topcat 
i.e. `>> topcat Template_{OBJNAME}_tellu_obj_AV.fits`

Columns are as follows:
- Filename
- OBJNAME
- BERV
- SNR33
- MidObsMJD
- Processed Date
- the calibration files that were used
