### ISSUE TITLE
Duplicate cal_flat_spirou entries in log.fits

### ISSUE THREAD

**Issue by CharlesCadieux** [njcuk9999/apero-drs#658]
For an unique PID, 7 cal_flat_spirou entries are entered in the reduced night log.fits.

The `LEVEL_CRIT` column indicates:
2 cal_flat_spirou for fiber A,
2 cal_flat_spirou for fiber B,
2 cal_flat_spirou for fiber C, 
1 cal_flat_spirou for fiber AB.

The extra recipes called for fiber A, B, and C lead to the same output, but have a different `PLOTDIR` value (set to None).

![image (3)](https://user-images.githubusercontent.com/47217750/105043475-91bf5700-5a33-11eb-8a5a-0b0b9518846f.png)

**Comment by njcuk9999** [comment]
Not sure of the cause of this.

The expected outcome should be for `LEVEL_CRIT` should be
```
num=0 fiber = AB
num=0 fiber = A
num=0 fiber = B
num=0 fiber = C
```

so only 4 entries for a single PID. 
Weird...
