### ISSUE TITLE
source apero.bash.setup fails

### ISSUE THREAD

**Issue by jorgehumberto** [njcuk9999/apero-drs#667]
❯ source apero.bash.setup
    Traceback (most recent call last):
      File .../apero/tools/recipes/bin/apero_validate.py", line 101, in <module>
        ll = main()
      File ".../apero/tools/recipes/bin/apero_validate.py", line 64, in main
        recipe, params = core.setup(__NAME__, __INSTRUMENT__, fkwargs)
      File ".../apero/core/core/drs_startup.py", line 131, in setup
        pid, htime = _assign_pid()
      File ".../apero/core/core/drs_startup.py", line 1423, in _assign_pid
        unixtime, humantime, rval = unix_char_code()
      File ".../apero/core/core/drs_startup.py", line 1439, in unix_char_code
        time.sleep(rint)
TypeError: only integer scalar arrays can be converted to a scalar index

Changing `unix_char_code()` to 

---------------
    def unix_char_code():
        # we need a random seed
        np.random.seed(random.randint(1, 2**30))
        # generate a random number (in case time is too similar)
        #  -- happens a lot in multiprocessing
         rint = np.random.randint(1000, 9999, 1) / 1e7
        # wait a fraction of time (between 1us and 1ms)
    
        **time.sleep(float(rint))**
        # get the time now from astropy
        timenow = Time.now()
        # get unix and human time from astropy time now
        unixtime = timenow.unix * 1e7
        humantime = timenow.iso
        # generate random four characters to make sure pid is unique
        rval = ''.join(np.random.choice(list(CHARS), size=4))
        return unixtime, humantime, rval
---------------

fixed the issue.

Runing:
- FedoraRemix@WSL2 on Windows 10 Pro machine (Clevo P775-DMG3, i7-7700K, 64GB RAM)
- Python 3.8 on Anaconda

**Comment by njcuk9999** [comment]
Hi @jorgehumberto  this has been corrected in our 0.7 branches quite a while ago (this will be python 3.8 compatible).

Note for the 0.6.131 and 0.6.132 version python 3.8 is not supported.

I assume you were using the master branch )v0.6.131) as this was also fixed in the developer branch (currently on v0.6.132) - I would suggest using the developer branch

**Comment by jorgehumberto** [comment]
OK, thank you, I'll move to the dev branch then!

Closing.
