### ISSUE TITLE
Error installation V7 KeyError: 'DEVMODE'

### ISSUE THREAD

**Issue by andrescarmona** [njcuk9999/apero-drs#669]
Error during the installation

python setup/install.py

the error happens when introducing the SQL data base details

*********************************
For MySQL you must define some parameters, these will take the form:
        >> mysql -h {HOSTNAME} -n {USERNAME} -p {PASSWORD}
         - Note the password will be stored as plain text.

You will also need a database name (within mysql) 
        - if it does not exist we will attempt to create it (but may not have permissions to do so)
You may also link the database to a specific apero profile
        by default this is the profile name you set up here
        however you may want to link this database to another apero profile
Enter database {HOSTNAME}:
 >>   clusterdb
Enter database {USERNAME}:
 >>   acarmona
Enter database {PASSWD}:
 >>   db_for-apero
Enter mysql database name
 >>   aperodb
Enter table suffix for CALIB database table (leave blank for default: setup_mini2_07126) 
         Note "CALIB_{SUFFIX}_DB" will be the final table name. 
         i.e. by default: CALIB_setup_mini2_07126_DB
 >>   
Enter table suffix for TELLU database table (leave blank for default: setup_mini2_07126) 
         Note "TELLU_{SUFFIX}_DB" will be the final table name. 
         i.e. by default: TELLU_setup_mini2_07126_DB
 >>   
Traceback (most recent call last):
  File "/net/GSP/nas12c/big_spirou/APERO_V07_TEST/apero-drs/apero/core/constants/param_functions.py", line 158, in __getitem__
    return super(ParamDict, self).__getitem__(key)
  File "/net/GSP/nas12c/big_spirou/APERO_V07_TEST/apero-drs/apero/core/core/drs_base_classes.py", line 88, in __getitem__
    return self.data[key]
KeyError: 'DEVMODE'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup/install.py", line 583, in <module>
    main()
  File "setup/install.py", line 518, in main
    allparams, args = install.user_interface(params, args, LANGUAGE)
  File "/net/GSP/nas12c/big_spirou/APERO_V07_TEST/apero-drs/apero/tools/module/setup/drs_installation.py", line 510, in user_interface
    all_params = get_mysql_settings(all_params, args)
  File "/net/GSP/nas12c/big_spirou/APERO_V07_TEST/apero-drs/apero/tools/module/setup/drs_installation.py", line 762, in get_mysql_settings
    all_params = mysql_database_tables(args, all_params)
  File "/net/GSP/nas12c/big_spirou/APERO_V07_TEST/apero-drs/apero/tools/module/setup/drs_installation.py", line 811, in mysql_database_tables
    if database_ask[db_it] or all_params['DEVMODE']:
  File "/net/GSP/nas12c/big_spirou/APERO_V07_TEST/apero-drs/apero/core/constants/param_functions.py", line 161, in __getitem__
    raise DrsCodedException('00-003-00024', targs=[key], level='error',
apero.core.core.drs_exceptions.DrsCodedException: 14:37:13.263-*|param_functions.py.ParamDict.__getitem__()|E[00-003-00024] ParamDict Error: Parameter 'DEVMODE' not found in parameter dictionary

If you suspect this is an IPython 7.21.0 bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

**Comment by njcuk9999** [comment]
Thanks Andres, no idea where this bug came from - I confirm I also got this on trying it today (so I have changed something that broke this since I last tested the installer).

Luckily this was a simple bug - it is fixed now - so update the branch with:
```
git pull origin v0.7.126-stable-test
```

and you should be good.

Note there were two typos in my instructions:

- step 2e: `pip install -r requirements_developer.txt` --> `pip install -r requirements_test.txt`
- step 3a: `python setup/install.py setup_mini2_07126` --> `python setup/install.py --name=setup_mini2_07126`


Annoyingly for step 2e it means you will need to remove the conda environment and re-make it
```
conda remove --name myenv --all
```

**Comment by andrescarmona** [comment]
Excellent Neil,

Now its working!!! 

Andres
