### ISSUE TITLE
Bimodal behavior of CCFMNRV in C channel in recent upsAnd series (C-channel SNR=400)

### ISSUE THREAD

**Issue by larnoldgithub** [njcuk9999/apero-drs#672]
Observations of Aug 14 and 18 of two long OG for Stefan Pelletier on upsAnd show weird behavior of the FP drift. The plots below show CCFMNRV versus time for the full night Aug 14 and 18.

Other transits or long OG observed this run do not show this behavior, SNR of the FP is usualy always lower.

I thought it was maybe related to the number of FP peaks extracted by the DRS, maybe an order where the number of peaks is switching between 2 values +/- randomly during the series. I tought it would change the wavesolution for that order and end in that 1.7m/s unstability.   I checked all log files APERO*cal_extract*log  but didn't find anything:  for a given order 0-48 the number of peaks is the same for all exposures. 

I'll explore the ccf logs also again.

Below are 2 plots for each night showing the issue with CCFMNRV and the measured SNR in the C-channel
![Screen Shot 2021-08-22 at 17 57 58](https://user-images.githubusercontent.com/59746974/130389082-5467d949-13bc-463c-82a3-3d6bdd3be12f.png)
![Screen Shot 2021-08-22 at 17 57 54](https://user-images.githubusercontent.com/59746974/130389085-f2f7b01f-c8b7-4533-bec7-a6d0c40dd46e.png)
![Screen Shot 2021-08-22 at 17 57 33](https://user-images.githubusercontent.com/59746974/130389087-b9611358-28db-465e-bdaf-fd4d43c6dd71.png)
![Screen Shot 2021-08-22 at 17 57 29](https://user-images.githubusercontent.com/59746974/130389089-a6f838cb-d801-41d9-a928-e0a4c158a5e1.png)

**Comment by larnoldgithub** [comment]
After the current run, I can do a test with short series of FP on AB and C with different SNR to see the SNR at which the issue with CCFMNRV occurs.

**Comment by njcuk9999** [comment]
The SNR is in which order? Do I read this graph as the SNR is exactly 400 everywhere or is the value of SNR > 400?

I don't think you can blame the wave solution for this - there should only be 2 wave solutions per night - one for the PM calibration and one for the AM calibration - it seems your oscillation here is within a night?  To be sure check which wave solution was used with each file for 59455.40 to 59445.60 - if they use one wave solution - then the wave solution is constant (so it cannot be a problem) if they use two (the PM and the AM) you could only see a jump from one to the other - the only way you could blame the wave solution is if it jumped from one wave solution to the other following your oscillation - I cannot see any way this could happen in the DRS.

You should probably isolate the oscillating data and plot some of the orders in the extracted spectrum:

i.e. plot order the e2dsff for order 35 for the observations from 59445.40 to 59445.60 and see if you can see any change.

Note that extraction is simple (not much from the drs can go wrong) it just takes the pixels in the location and sums them - if there is something wrong there it is most likely something wrong with the raw data itself (i.e. not a DRS problem).

If I recall correctly this star (upsAnd) is extremely bright, correct? the FP ND is normally adjusted to match the brightness of the star correct? This would explain your high SNR FPs? If I had to blame anything it would be that - maybe the FP are saturated or pushing the FP that bright means the FP peaks do not look "normal" the ND adjustment just doesn't work for this magnitude? - I think plotting the e2dsff for "normal" and your "oscillating" cases will show you interesting things and maybe explain it or at least show you weird things happening - if they look completely "normal" then maybe it is a drs issue.

**Comment by clairem789** [comment]
hi Luc, I've seen that the FP neutral density value is 0.82 for this sequence. It is in a range where I don't know the behaviour of the density. It is not a problem of saturation, because the SNR is not that large, in my opinion, but it could be that the ND has weird behavior at values <1 where it's never used... I would test that first...

**Comment by larnoldgithub** [comment]
Hi Neil  The SNR is extracted from order 34 (Y axis legend).  As Claire says, it is not saturating, but clearly the issue seems to be connected to the relatively high SNR in the FP C-channel.    yes the star is bright, set to H=3 in the observing tools (but it may be even brighter, as PI cannot enter H<3)  I'll have a look at the e2ds as you suggest

**Comment by larnoldgithub** [comment]
Hi Claire  testing the ND means doing the test I was mentioning in the comment I added yesterday, i.e. "short series of FP on AB and C with different SNR to see the SNR at which the issue with CCFMNRV occurs."

**Comment by larnoldgithub** [comment]
For the record: AB has SNR=600.

**Comment by larnoldgithub** [comment]
Hi Neil
You are correct about the WAVEFILE:  the only change occurs at midnight HST, and this leads to the -1.5m/s jump at 59441.418.

dfits -x 1 *o_pp_e2dsff_C_ccf_smart_fp_mask_C.fits |fitsort MJDATE HSTTIME CCFMNRV WAVEFILE WAVETIME OBJECT PI_NAME |grep Pelletier

**Comment by larnoldgithub** [comment]
I had a look at the fourth extension of the o.files,  many peaks in the H band do not reach the 14 reads, the brightest peaks in H seem to reach 8 counts before saturation.  I didn't try to see if these numbers fluctuate for a given pixel in the time series, but I can do it quite easily.  If I see fluctuation between 2 values, the slope would oscillate between 2 values too, but I don't see yet how it could lead to a bimodal behaviour of the drift.   I can extract an image for only say 7 reads, and see if the C channel behaves correctly. That's your idea @eartigau ?

**Comment by eartigau** [comment]
Having FP peaks that do not reach the number of reads in a frame is a very bad idea. You do not improve the photon noise and you will most likely have 2nd order effects where there is a coupling between an imperfect correction of linearity and RV. Do you see pixels on the science traces that do not reach the 14 reads? Can you check the median value of the intercept? That’s 3rd extension. If it fluctuates, then it adds a DC level to the slope fitting and the number of valid reads. I’m also a bit puzzled as to how this could translate into a bimodal distribution.

**Comment by larnoldgithub** [comment]
I plotted the Yintercept of a random point with NREADS=14 (nominal) and there is a bimodal distribution of the Yintercept:
![Screen Shot 2021-10-12 at 20 36 36](https://user-images.githubusercontent.com/59746974/137081511-6029ba8e-0e50-48c8-a560-69726cb87e05.png)

**Comment by larnoldgithub** [comment]
for both pixels, the variations are phased, only amplitude and mean value change.
Not all pixels with the nominal NREADS=14 shows this bimodal behavior:
![Screen Shot 2021-10-12 at 20 37 26](https://user-images.githubusercontent.com/59746974/137082045-565b8949-9ff4-4766-900e-5d50749cbb94.png)

**Comment by larnoldgithub** [comment]
on the plot below: Yintercept, slope and nreads for a given pixel. Only the Yintercept is bimodal.
![Screen Shot 2021-10-12 at 22 23 42](https://user-images.githubusercontent.com/59746974/137095898-ec1cf0c7-ffcf-47d2-8483-72f266ca56d2.png)
