### ISSUE TITLE
BERV calculation from a given input

### ISSUE THREAD

**Issue by clairem789** [njcuk9999/apero-drs#675]
I put this second issue with a different question/impact, still related to BERV calculation. For an identical input, we find for some stars different BERV calculated with barycorrpy (outside apero) and with apero. Merwan can give examples (he can't create issues for some reason, that's why I'm starting this!!)

**Comment by njcuk9999** [comment]
I would need Merwans github username to add him to collaborators.
As in the other thread - we know there are problems with the BERV in 0.6 - in 0.7 the BERV stuff has nearly been completely re-written.

I'm not sure what you mean by "identical input" getting a different BERV?
Do you mean the exact same pp file run twice in a row is giving different results?
Or do you mean you have run a pp file now and are comparing it to an old run?

Have you checked the the `BC_` keys for these e2dsff files (where you say the BERV is different?)

i.e. these keys:
BC_GAIA =   909820931110880640 / The Gaia ID used for BERV params
BC_OBJNM= '33Lyn   '           / The OBJNAME used for BERV params
BC_RA   =    128.6827139477187 / Right Ascension used to calc. BERV
BC_DEC  =    36.41944482164627 / Declination used to calc. BERV
BC_EPOCH=    2457205.999994213 / Epoch [JD] used to calc. BERV
BC_PMRA =   -26.11661600568005 / PMRA [mas/yr] used to calc. BERV
BC_PMDE =   -40.89996873740448 / PMDE [mas/yr] used to calc. BERV
BC_LAT  =            19.825252 / OBS Latitude [deg] used to calc. BERV
BC_LONG =          -155.468876 / OBS Longitude [deg] used to calc. BERV
BC_ALT  =               4204.0 / OBS Altitude [m] used to calc. BERV
BC_PLX  =    9.995273103686801 / PLX [mas] used to calc. BERV
BC_RV   =                  0.0 / RV [km/s] used to calc. BERV
BC_PSRCE= 'GAIA [TABLE]'       / Source of BERV star params
BC_GMAG =    5.730706214904785 / Gaia G mag for BERV calc.
BC_BPMAG=    5.770686149597168 / Gaia BP mag for BERV calc.
BC_RPMAG=    5.689286231994629 / Gaia RP mag for BERV calc.
BC_MAG_L=                 15.0 / Gaia mag lim for BERV calc.
BC_PLX_L=                  5.0 / Gaia plx lim for BERV calc.


If any of these are different between the e2dsff files you will get a different BERV value.
These are literally the values that go into barycorrpy (along with the MJDMID) so also check that your MJDMID is the same (or very similar)

Now if these are identical for your e2dsff files AND your e2dsff files were produced at the same time then we have a problem that I don't know the cause of!

So please more details!

**Comment by HkmMerwan** [comment]
Hi Neil, my username is this one.

Yes the headers are different with the value I get using the barycorrpy function to get stellar data. However as showed in the other issue I do not get the same BERV even when running barycorrpy with the inputs of the header, at least not all the time.

This issue has been opened to show a different error in the BERV correction that shows clearly for a few stars.

When computing the BERV with 

```
from barycorrpy import get_BC_vel , exposure_meter_BC_vel
from barycorrpy.utils import get_stellar_data
get_stellar_data(target)

stellar_data = get_stellar_data(target)[0]
ra = stellar_data['ra']
dec= stellar_data['dec']
obsname=''
lat=19.825252
longi=-155.468876
alt=4204.0
pmra = stellar_data['pmra']
pmdec = stellar_data['pmdec']
px = stellar_data['px']
rv = stellar_data['rv']
epoch = stellar_data['epoch']
ephemeris='https://naif.jpl.nasa.gov/pub/naif/generic_kernels/spk/planets/a_old_versions/de405.bsp'
JDUTC=Time(time_spirou, format='mjd', scale='utc') # Can also enter JDUTC as float instead of Astropy Time Object
zmeas=0.0
barcorrpy =get_BC_vel(JDUTC=JDUTC, ra=ra, dec=dec, obsname=obsname, lat=lat, longi=longi, alt=alt, pmra=pmra,
            pmdec=pmdec, px=px, rv=rv, zmeas=zmeas,epoch=epoch, ephemeris=ephemeris, leap_update=True)
barcorrpy = barcorrpy[0]
```

And plotting the BERV difference between this berv and the one from the DRS (which I get from the lbl file but I did check that it is the same in all the spectrum files) in red anb by overplotting the lbl RV of the star (in black) it is obvious that there is a BERV residual in the star data. Here are the 3 stars for which it is the more apparent : 

![image](https://user-images.githubusercontent.com/76592606/135464957-e2fcc0c7-ed96-4f39-b222-f7d7f258e3eb.png)

**Comment by njcuk9999** [comment]
Okay Claire asked me to remove the plots after seeing them - we will have to share them another way that isn't public.


I'm not sure I'm seeing the difference between these two issues? They both seem related to the BERV?

So I'll just echo what I said in the other issue.
1. plot the BERV only for each observations (no LBL) for your parameters and the drs parameters
2. look at the input parameters themselves between "your parameters" and the drs parameters - whats the difference and by how much are the different? Are the drs 0.6 values just wrong completely or slightly wrong?

If we are blaming the BERV alone we can take this problem away from the DRS and LBL - we have the parameters which were used in the headers of the e2ds files - and you obviously have your stellar parameters somewhere - so we can really make this a standalone issue and see what is going on

**Comment by HkmMerwan** [comment]
There are two issues, both BERV related:

- when computing barycorrpy with the same parameters as the DRS I do not have the same BERV value for all stars. (the other issue)
- when computing barycorrpy with the parameters from get_stellar_data it can be seen that the BERV difference between my BERV and the BERV from the DRS is responsible for the trend of some stars

**Comment by HkmMerwan** [comment]
Moved the discussion to slack.
