### ISSUE TITLE
Remove calls to deprecated `DataFrame.append()` method from Pandas

### ISSUE THREAD

**Issue by vandalt** [njcuk9999/apero-drs#693]
I got this warning message when running `apero_astrometrics.py`

```Python
/cosmos99/nirps/apero-bin/apero-drs/apero/tools/module/database/drs_astrometrics.py:1133: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  dataframe = dataframe.append(astro_obj.to_dataframe())
```

EDIT: warning, not error

**Comment by njcuk9999** [comment]
Error or a warning? It worked fine in the apero-env environment on nirps-client. Where are you using it?

**Comment by vandalt** [comment]
Warning, sorry, I updated my comment above. Also this is the related Pandas announcement (with new recommended syntax): https://pandas.pydata.org/docs/whatsnew/v1.4.0.html#whatsnew-140-deprecations-frame-series-append

**Comment by njcuk9999** [comment]
I've updated this now.
