### ISSUE TITLE
[APERO] non_dealloc: deallocating None error

### ISSUE THREAD

**Issue by njcuk9999** [njcuk9999/apero-drs#707]
First reported by @larnoldgithub 

In apero_precheck

Error:

```
Fatal Python error: none_dealloc: deallocating None
Python runtime state: initialized
```

Happens in:
```
apero/core/core/drs_database.py line 2226 update_entries
apero/core/core/drs_database.py line 1842 in add_entry
```

**Comment by njcuk9999** [comment]
Doesn't seem to have come back. Closing for now.

**Comment by njcuk9999** [comment]
Okay happened to me.

This seems to be a similar problem reported here: https://stackoverflow.com/questions/76193436/fatal-python-error-none-dealloc-deallocating-none-bug-likely-caused-by-a-refc


The solution seems to be to upgrade to python 3.12 or downgrade to mysql-connector-python==8.0.20

**Comment by njcuk9999** [comment]
@larnoldgithub the downgrade of mysql-connectoer-python may be the solution for you until I support python 3.12

I'll put it into the requirements to use this older version.

**Comment by larnoldgithub** [comment]
Does the downgrade require a complete reinstall ? or is it possible to just update that package ?  I'll ask Chris to do that when your requirements are updated

**Comment by cusher** [comment]
Wow, good find! I was able to use that info to track down a corresponding bug report: https://bugs.mysql.com/bug.php?id=111111

According to that, it has also been fixed in version 8.1.0. That appears to be confirmed in the release notes here: https://dev.mysql.com/doc/relnotes/connector-python/en/news-8-1-0.html

**Comment by larnoldgithub** [comment]
After downgranding  to mysql-connector-python==8.0.20 the precheck on the full SPI data set (99000 files) took about 4h with no errors.

**Comment by njcuk9999** [comment]
@cusher wow great job finding the bug report! I'll test out 8.1.0 for future releases.
