### ISSUE TITLE
running LBL on LFC files

### ISSUE THREAD

**Issue by clairem789** [njcuk9999/apero-drs#721]
I tried running LBL on LFC files, AB and C separately. 
The template looks good.
The trumpet plot looks like this: no RV values between 1300nm and 2200nm, where the flux is the best. sdv values exist and are of good quality for this range. What could have gone wrong?
![lfc2023](https://github.com/njcuk9999/apero-drs/assets/32554392/e8d87902-9247-4b81-af5a-6628eef0cedd)

**Comment by njcuk9999** [comment]
This is an LBL issue so I'll move it to https://github.com/njcuk9999/lbl/issues/36
