### ISSUE TITLE
Installing v0.7.288 on NewWorlds (Toulouse)

### ISSUE THREAD

**Issue by clairem789** [njcuk9999/apero-drs#722]
I tried installing v0.7.288 in Toulouse, doing:
```
conda create --name=ap288 python=3.9
conda deactivate
conda deactivate
conda deactivate
conda deactivate
conda activate ap288
cd apero-drs
git fetch
git branch
git checkout v0.7.288-stable-test
pip install -r requirements_developer.txt
python setup/install.py --name=ap288
```
 I got this error message during install.py:

Settings for SPIROU
===================================================================
Traceback (most recent call last):
 File “/Users/moutou/apero-drs/setup/install.py”, line 669, in <module>
  main()
 File “/Users/moutou/apero-drs/setup/install.py”, line 598, in main
  allparams, args = install.user_interface(params, args, language)
 File “/Users/moutou/apero-drs/apero/tools/module/setup/drs_installation.py”, line 470, in user_interface
  value = getattr(args, DATA_ARGS[path])
AttributeError: ‘Namespace’ object has no attribute ‘lbldir’

Any ideas what I got wrong?
Thanks!

**Comment by njcuk9999** [comment]
Hmm okay weird I did test this but then I may have made some changes afterward, I'll look into this.

**Comment by eartigau** [comment]
I have the least helpful comment: It worked on my laptop … I have no clue as to why it doesn’t work on your machine! I did have to force install a few packages version with pip as I got an error message at the end of the pip install -r requirements_developer.txt

**Comment by njcuk9999** [comment]
what was the error at the end of the pip install command?
That may need to be another issue (or at least sorted out) unless you did something "undesirable".

**Comment by njcuk9999** [comment]
Oh saying that @clairem789  you are missing a command:
```
conda activate ap288
```
(before the pip install)

Though this may just be a typo on your part - it would mean you've screwed up your `conda` base environment (and now have packages installed on the base) which would require a reinstall of `miniconda` 

same for your @eartigau, actually this may be why you got a pip error - you already have stuff on your base env (which should be empty)

**Comment by njcuk9999** [comment]
I actually get the same error as @clairem789  so I'm not sure how yours worked @eartigau.

**Comment by njcuk9999** [comment]
Okay, I've fixed it for me, it was a small typo not sure when I introduced that.
@clairem789 let me know if it works for you!
I'm going to update your original message with the missing command, just in case someone finds this and tries to install stuff.

**Comment by clairem789** [comment]
OK this worked. It's running. Thanks!

**Comment by clairem789** [comment]
hi all, I ran the v288 on the minidata set. It terminated quietly. 
There is, however, a problem with the drift file. If I show you the first 3 columns of it:
cat drift.rdb |awk '{print $1,$2,$3}'
rjd vrad svrad
N N N
59030.89990958315 -13.688763157518009 0.03322393844511832
59064.900207214036 -0.9807136002033332 0.017711118724625784
59092.90154091403 4.354826159286845 0.023352164214961932
59129.90622941403 14.984310847383584 0.02847004634416082
59065.90160090403 -0.5337401848550704 0.016514566422963887
59063.89836258404 -2.3229601337810357 0.018665750734734487
59115.90494660403 10.607819193017775 0.02952680055619064
58983.90483704314 -24.74407709082389 0.06184237365135822
59059.903573423144 -1.6345180818702645 0.039357397401199916
59060.89786008402 -1.3427143219147544 0.01811968143410379
59062.90343965402 -2.570887800765612 0.018193743193838
59071.899735274026 0.02596114969609671 0.018606732276776998
59154.90748468404 19.23515729628556 0.03180416273350041

So, it's very small and contains only the calibrations, not the Gl699 simultaneous drift measurements. I didn't see an obvious error popping up.
Do you have a similar problem? What can I fix? thanks!

**Comment by njcuk9999** [comment]
I haven't checked myself.

Could you check what is in the `/lbl/science/FP` directory?  It may be that I only copied the `FP_FP` files and need to add the simultaneous FP files there too.

**Comment by clairem789** [comment]
Yes, this is it!

**Comment by njcuk9999** [comment]
Okay I'll look over my code and make sure it is copying them, if it is already then I'll probably ask you more. Thanks for testing it!

**Comment by njcuk9999** [comment]
Okay I've found the problem, for DPRTYPE I was just getting `OBJ_FP` (this works for NIRPS) but for spirou I also need to look for `DPRTYPE=POLAR_FP`   (and all GL699 are POLAR_FP in this case).

I've updated v0.7.288-stable-test so a `git pull` at your end should do it. You can either run the full mini run again, or first check with a new run.ini similar to the `lbl_run.ini` (though you may have to update it to match the mini run settings with `SCIENCE_TARGETS` etc).

**Comment by clairem789** [comment]
I confirm the test runs great with this new version. This is the content of the final file, obtained with  : 

cat lbl2_GL699_GL699_drift.rdb |awk '{print $1,$2,$3}'

rjd vrad svrad
N N N
58984.05390878429 -110193.21788971453 0.9343694308854495
59030.93447572854 -110194.41180462166 0.9862917202035016
59059.86752607301 -110200.42317944583 0.8300514678547082
59060.8571271227 -110194.98335332949 0.7578102092137656
59062.883282140596 -110198.11619409005 0.7481104646586443
59063.77909281326 -110200.81693833967 1.0866472197376829
59064.896404195344 -110196.53830306236 0.8103029075121354
59065.83420328738 -110198.98893844377 0.7569455412705957
59071.83309346251 -110198.83668472123 0.809213616049847
59092.7195982578 -110198.28948795485 0.9288271950084797
59115.702675125794 -110193.74603541825 0.8347963663131514
59129.76672036934 -110196.10300444231 0.780737870584925
59154.68532708858 -110193.4961615487 0.8222449809959744

Shall we re-reduce all data? or wait for a proper comparison between places?

**Comment by njcuk9999** [comment]
If you can just drop your GL699_GL699 files in here: https://drive.google.com/drive/folders/1XpgLS_mD0-vZXMFIJCblZPoKBsC0xoC1?usp=sharing

You should be able to drop stuff in there after signing in to gmail (I think)

Maybe the lbl, lbl2, drift GL699_GL699

I've put a directory in there called `v0.7.288-stable-test`  and a sub-directory for each data set

If I have time I'll compare but I'll also drop my data in there so others can compare

**Comment by clairem789** [comment]
OK, thanks; file transfer done on my side. Rali versus NewWorlds:

# comparison on lbl2_GL699_GL699_drift.rdb
std dev NW/RALI (m/s) =  2.5535928784049684 2.551991094348238
RMS of difference (m/s) =  0.05231690143588415

# comparison on drift.rdb
std dev NW/RALI (m/s) =  5.021218915648642 5.0218668753135765
RMS of difference (m/s) =  0.0037176083757248157

**Comment by njcuk9999** [comment]
I actually realized the `rali` ones weren't the most up-to-date version of v0.7.288 so I've re-run them today (with the other machines) I'll upload them as soon as they are done.

2.5 m/s seems a lot - I imagine it's probably the LBL again - this is something to fix on my return - or maybe bug @eartigau about it in the meantime.

I guess we should also upload our tcorr files + blaze files so someone could run lbl on all versions and/or compare the tcorr themselves - that would be the next step: really understanding where the difference starts!

**Comment by njcuk9999** [comment]
Lets continue the comparison discussion here: https://github.com/njcuk9999/apero-drs/issues/708
