### ISSUE TITLE
error with pip install -r requirements_current.txt  (0.7.288)

### ISSUE THREAD

**Issue by larnoldgithub** [njcuk9999/apero-drs#729]
ERROR: Cannot install -r requirements_current.txt (line 14), -r requirements_current.txt (line 15), -r requirements_current.txt (line 23) and pandas==2.0.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested pandas==2.0.1
    pandastable 0.13.1 depends on pandas>=1.5
    pandasql 0.7.3 depends on pandas
    lbl 0.63.2 depends on pandas==2.0.2

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

-----

I've edited the requirements_current.txt file I have on my machine  to pandas==2.0.2

error is fixed.

**Comment by njcuk9999** [comment]
Sorry, the `requirements_developer.txt` is correct. I'll patch the `requirements_current.txt` note you should probably use the `requirements_developer.txt` for experimental versions of the code.
