### ISSUE TITLE
Wrong labelling of atmospheric molecules in tapas_all_sp.fits (fields of the fits table)

### ISSUE THREAD

**Issue by larnoldgithub** [njcuk9999/apero-drs#742]
For the record, the labels for each field are incorrect, but for water.
Water and all other 'dry' species are handled separately in APERO so it's not a big deal if it's named for example N2O while it's CO2...

FITS file: tapas_all_sp.fits
 
Extension No: 1
FITS Binary Table: Size 64 by 374499
Field           Name Unit Frmt Null Comment
    1     wavelength         D      
    2      trans_h2o         D      
    3       trans_o3         D      
    4      trans_n2o         D      
    5       trans_o2         D      
    6      trans_co2         D      
    7      trans_ch4         D      
    8 trans_combined         D      

actually, it should be:
Field           Name 
    1     wavelength             
    2      trans_h2o        (white)    
    3       trans_ch4       (blue)   
    4      trans_co2       (orange)
    5       trans_no2      (yellow) 
    6      trans_ o2         (red)
    7      trans_o3          (purple)

![tapas-templates](https://github.com/njcuk9999/apero-drs/assets/59746974/9c2e2dea-e8bb-4180-afc1-7a2dd34b5fd9)

**Comment by njcuk9999** [comment]
@eartigau  created this file manually I think so it may not be exactly as downloaded. I will let him comment on this. As you say they are all bundled in to dry components so as long as water is correct apero works correctly but we should have the correct labels.

**Comment by njcuk9999** [comment]
So I just got @eartigau to confirm, we did have them mislabeled (I thought he might have just rearranged the columns).
I'll add these to a few other bug fixes for v0.7.289.

Note that this doesn't affect anything in the apero codes (as you say they all get merged to "dry") it will just affect the fits file itself.
