### ISSUE TITLE
error with reject database

### ISSUE THREAD

**Issue by andrescarmona** [njcuk9999/apero-drs#749]
10:29:16.745-!!|PROC| 10:29:16.621-**|DatabaseError|E[00-002-00032] <class
10:29:16.745-!!|PROC|   'mysql.connector.errors.DatabaseError'>: 1030 (HY000): Got error 168 "Unknown
10:29:16.745-!!|PROC|   (generic) error from engine" from storage engine InnoDB
10:29:16.746-!!|PROC|    Command: DROP TABLE reject_full_v07288_db
10:29:16.747-!!|PROC|   path: /home/external/acarmona/.apero/acarmona_at_clusterdb
10:29:16.747-!!|PROC|   Function: apero.base.drs_db.py.Database.execute()
10:29:16.914-**|PROC| ***************************************************************************
10:29:16.947-@!|PROC| W[40-003-00005]: Recipe apero_processing has NOT been successfully completed
10:29:16.993-**|PROC| ***************************************************************************

It was solved not updating the reject database.  Ideas?

**Comment by njcuk9999** [comment]
No idea with "Unknown (generic) error from engine"

Can you access the reject database via mysql?
Seems to be a problem removing the table (the command that was used was "DROP TABLE reject_full_v07288_db")

Did you try again?

**Comment by andrescarmona** [comment]
Hello Neil,

I did launch the reduction without updating the reject database.

Launched again and same problem. 

As this is the reduction of a new run, I will just go on until i am up to date on
the reduction without updating the reject database :-)

Andres

**Comment by njcuk9999** [comment]
Okay but we should fix the problem at some point.

Once you are ready to try, I need you to:

1. Try to access the reject database from mysql
2. Backup the table (there are mysql commands to duplicate the table) then try dropping the table in mysql 

If both of those work I'm not sure what could cause this. If there is an error in any of these maybe the error can help us.

**Comment by njcuk9999** [comment]
@andrescarmona given your email about running out of space for the mysql database, this issue may be directly linked to that!

**Comment by andrescarmona** [comment]
I hope, I can not run APERO at all now..

**Comment by andrescarmona** [comment]
APERO went back to operations. The solution was:
1) liberate disk space, we moved from 94% to 77%
2) reboot the database server

**Comment by andrescarmona** [comment]
the actualisation of the reject database worked too.
