### ISSUE TITLE
Pass along threaded into DRS startup

### ISSUE THREAD

**Issue by cusher** [njcuk9999/apero-drs#777]
On branch: `v0.7.289-stable-test`

There is a `threaded` param in `drs_startup.setup` that must be set to `True` when being called in a subprocess, otherwise the call to the `signal` function throws an error. However since this param is outside of `fkwargs`, there doesn't seem to be a way to pass this in through any of the usual ways (e.g. `main()` params, command line args, run.ini config) and it has to be manually passed, in the recipe code when `drs_startup.setup` is called, e.g.
```
recipe, params = drs_startup.setup(__NAME__, __INSTRUMENT__, threaded=kwargs.get('threaded')
```

Not sure if this is intended or there's another way to get around this...

**Comment by njcuk9999** [comment]
Hmm okay, I could also push it via `fkwargs`  which is used to pass any argument from a recipes `main()` function.

The this line:
```python
def setup(...):

    ... 

    # catch sigint (if not threaded) -- if threaded can only be in main thread
    if not threaded:
        signal(SIGINT, constants.catch_sigint)
```

becomes:
```python
def setup(...):

    ... 

    # catch sigint (if not threaded) -- if threaded can only be in main thread
    if not fkwargs.get('threaded', threaded):
        signal(SIGINT, constants.catch_sigint)
```


If you need a command line argument its harder, as the parsing is done later.

**Comment by cusher** [comment]
That should deal with my use case, the only one I actually care about for the trigger is indeed when calling `main()`.

FWIW I think it should be okay to ignore the case of command line arguments here, since really starting it in a child python thread by calling it from the command line seems like a pretty niche way to do this in the first place.
