### ISSUE TITLE
adding new dates in the ini file?

### ISSUE THREAD

**Issue by clairem789** [njcuk9999/apero-drs#778]
hi all,

I tried running the latest data from SPIRou, and this is what I got. It seems to have to do with the list of new dates. It seems to me I did as ever (insert of the ini file below), but it doesn't like it anymore. Do you have a clue? thanks!

15:18:11.074-!!|PROC| E[01-010-00001]: Unhandled error has occurred: Error <class 'KeyError'>
15:18:11.075-!!|PROC| 
15:18:11.075-!!|PROC| Traceback (most recent call last):
15:18:11.075-!!|PROC|  File "/Users/moutou/apero-drs/apero/core/utils/drs_startup.py", line 433, in run
15:18:11.076-!!|PROC|    llmain = func(recipe, params)
15:18:11.076-!!|PROC|  File "/Users/moutou/apero-drs/tools/bin/apero_processing.py", line 208, in __main__
15:18:11.076-!!|PROC|    raise e
15:18:11.076-!!|PROC|  File "/Users/moutou/apero-drs/tools/bin/apero_processing.py", line 135, in __main__
15:18:11.077-!!|PROC|    manage_databases.update_reject_database(params)
15:18:11.077-!!|PROC|  File "/Users/moutou/apero-drs/apero/tools/module/database/manage_databases.py", line 834, in update_reject_database
15:18:11.077-!!|PROC|    maintable = get_reject_database(params, log=log)
15:18:11.077-!!|PROC|  File "/Users/moutou/apero-drs/apero/tools/module/database/manage_databases.py", line 900, in get_reject_database
15:18:11.078-!!|PROC|    maintable = _force_column_dtypes(maintable, REJECT_DATA_TYPES)
15:18:11.078-!!|PROC|  File "/Users/moutou/apero-drs/apero/tools/module/database/manage_databases.py", line 997, in _force_column_dtypes
15:18:11.078-!!|PROC|    values = np.array(table[col]).astype(coltype[col])
15:18:11.078-!!|PROC| KeyError: 'DATE_ADDED'

ini file contains:
INCLUDE_OBS_DIRS = 2024-06-25, 2024-06-26, 2024-06-27, 2024-06-28, 2024-07-17, 2024-07-18, 2024-07-19, 2024-07-20, 2024-07-21, 2024-07-22, 2024-07-23, 2024-07-24, 2024-07-25, 2024-07-26

**Comment by njcuk9999** [comment]
Hi Claire, can you make sure you are up-to-date? I had to issue a patch a while back so I could add columns in future versions.
Just let me know if a `git pull` does anything (and if not which branch you are on)

**Comment by clairem789** [comment]
You are right! A git pull did solve the problem! great, thanks
