### ISSUE TITLE
dependencies LBL  installation error  in APERO v07291

### ISSUE THREAD

**Issue by andrescarmona** [njcuk9999/apero-drs#795]
ERROR: Cannot install -r requirements_current.txt (line 21), -r requirements_current.txt (line 25), -r requirements_current.txt (line 5) and scipy==1.10.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested scipy==1.10.0
    barycorrpy 0.4.4 depends on scipy
    scikit-image 0.19.3 depends on scipy>=1.4.1
    lbl 0.64.16 depends on scipy==1.10.1

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip to attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

**Comment by njcuk9999** [comment]
Okay do a `git pull` on `v0.7.291-stable-test` and it should work now.

**Comment by andrescarmona** [comment]
I did it ! it is working now!!

**Comment by andrescarmona** [comment]
THAAANKS!
