### ISSUE TITLE
astrom database not found

### ISSUE THREAD

**Issue by clairem789** [njcuk9999/apero-drs#799]
I'm in the process of running the mini data set on a newly installed database (version/user/db).
When I try to run apero_processing on it, I get the following error:
(also copying the blue lines where all db tables are listed)
16:50:53.378-**|PROC|   DATABASE-calib: spirou@localhost:calib_md1011_db
16:50:53.379-**|PROC|   DATABASE-tellu: spirou@localhost:tellu_md1011_db
16:50:53.379-**|PROC|   DATABASE-findex: spirou@localhost:findex_md1011_db
16:50:53.379-**|PROC|   DATABASE-log: spirou@localhost:log_md1011_db
16:50:53.379-**|PROC|   DATABASE-astrom: spirou@localhost:astrom_md1011_db
16:50:53.379-**|PROC|   DATABASE-lang: spirou@localhost:lang_md1011_db
16:50:53.380-**|PROC|   DATABASE-reject: spirou@localhost:reject_md1011_db
16:50:53.380-**|PROC|   PRINT_LEVEL: all
16:50:53.380-**|PROC|   LOG_LEVEL: all
16:50:53.380-**|PROC|   DRS_PLOT: 0
16:50:53.386-  |PROC| ***************************************************************************
16:50:53.392-**|PROC| Arguments used:
16:50:53.399-**|PROC| 
16:50:53.399-**|PROC|   --RUNFILE: mini_run2.ini
16:50:53.405-  |PROC| ***************************************************************************
(and then the error)
16:50:54.379-!!|PROC| 16:50:54.371-**|DatabaseError|E[00-002-00053] Database table
16:50:54.379-!!|PROC|   "astrom_md1011_db" not found in database
16:50:54.379-!!|PROC|   path: /Users/moutou/.apero/spirou_at_localhost
16:50:54.380-!!|PROC|   Avaiable tables: 
16:50:54.380-!!|PROC|           - calib_md1011_db
16:50:54.380-!!|PROC|           - findex_md1011_db
16:50:54.381-!!|PROC|           - log_md1011_db
16:50:54.381-!!|PROC|           - tellu_md1011_db
16:50:54.381-!!|PROC|   Function: apero.base.drs_db.py.Database._infer_table_()
16:50:54.394-**|PROC| ***************************************************************************
16:50:54.401-@!|PROC| W[40-003-00005]: Recipe apero_processing has NOT been successfully completed
16:50:54.401-@!|PROC|   (1.818 seconds)

Same result with UPDATE_OBJ_DATABASE = True or False
What did I get wrong this time??
thanks

**Comment by njcuk9999** [comment]
I can't see anythign wrong from there. 

You could try a reset (`apero_reset.py`)

If that doesn't work could you go into mysql directly

i.e. command line: `mysql -h {host} -u {username} -p` 

where `{host}` is `localhost` in your case, and `{username}` is the one you entered when running `setup/install.py`

Then type `SHOW DATABASES;`

Then `USE {database}`

where `{database}` is the name of the one you entered when running `setup/install.py`

then type `SHOW TABLES;`

and then tell me whether `astrom_md1011_db` is in that list


Also if you could navigate to where your `user_config.ini` and `user_constants.ini` file are and show me the contents of `database.yaml` file, that would be great!

**Comment by clairem789** [comment]
database.yalm:
  ASTROM:
    NAME: 'NULL'
    PATH: 'NULL'
    PROFILE: md1011
    RESET: reset.astrom.csv

mysql database:
MariaDB [spirou]> show tables;
+------------------+
| Tables_in_spirou |
+------------------+
| calib_md1011_db  |
| findex_md1011_db |
| log_md1011_db    |
| tellu_md1011_db  |
+------------------+
4 rows in set (0,000 sec)

So no, astrom_md1011_db is not there.
Starting from scratch, maybe it should have downloaded a reference astrometric db from Montreal?

**Comment by clairem789** [comment]
That was my wrong doing with the install. For some reason I had one try where the "reset All" did not reach the db so in my second try I passed the reset (reply no) since there was no data and no table to clean; but this prevented the astrom db to be downloaded, hence the error!
